import AppKit
import ApplicationServices

/// Orders native status-item events through their owner and the window server.
/// Watches only tagged events generated by Arc; other input passes through.
@MainActor final class MenuPocketEventDelivery {
    private var events: [CGEvent] = []
    private var owner: pid_t = 0
    private var probe: CGEvent?
    private var processTap: CFMachPort?
    private var sessionTap: CFMachPort?
    private var sources: [CFRunLoopSource] = []
    private var timeout: Task<Void, Never>?
    private var marker: Int64 = 0
    private var release: CGEvent?
    private var savedPointer: CGPoint?
    private var pointerHidden = false
    private var pointerTask: Task<Void, Never>?
    var isBusy: Bool { !events.isEmpty }

    func send(_ events: [CGEvent], owner: pid_t, release: CGEvent) -> Bool {
        guard !isBusy, !events.isEmpty else { return false }
        // A previous delayed cleanup must not warp over a new user click.
        pointerTask?.cancel()
        pointerTask = nil
        if pointerHidden { NSCursor.unhide(); pointerHidden = false }
        savedPointer = CGEvent(source: nil)?.location
        if savedPointer != nil { NSCursor.hide(); pointerHidden = true }
        self.events = events
        self.owner = owner
        self.release = release
        return beginEvent()
    }

    func cancel() {
        let wasBusy = isBusy
        clearTaps()
        events.removeAll()
        if wasBusy { release?.post(tap: .cgSessionEventTap) }
        release = nil
        restorePointer(immediately: true)
    }

    private func restorePointer(immediately: Bool) {
        pointerTask?.cancel()
        pointerTask = nil
        guard let point = savedPointer else { return }
        if immediately {
            CGWarpMouseCursorPosition(point)
            savedPointer = nil
            if pointerHidden { NSCursor.unhide(); pointerHidden = false }
            return
        }
        // The owner can still handle the forwarded mouse-up after receipt.
        pointerTask = Task { [self] in
            do { try await Task.sleep(for: .milliseconds(50)) } catch { return }
            CGWarpMouseCursorPosition(point)
            savedPointer = nil
            pointerTask = nil
            if pointerHidden { NSCursor.unhide(); pointerHidden = false }
        }
    }

    private func beginEvent() -> Bool {
        guard let event = events.first, let probe = CGEvent(source: nil) else {
            cancel()
            return false
        }
        marker = Int64.random(in: 1..<(Int64.max - 1))
        event.setIntegerValueField(.eventSourceUserData, value: marker)
        probe.setIntegerValueField(.eventSourceUserData, value: marker + 1)
        self.probe = probe
        let context = Unmanaged.passUnretained(self).toOpaque()
        processTap = CGEvent.tapCreateForPid(pid: owner, place: .tailAppendEventTap,
            options: .defaultTap, eventsOfInterest: 1 << CGEventType.null.rawValue,
            callback: Self.callback, userInfo: context)
        sessionTap = CGEvent.tapCreate(tap: .cgSessionEventTap, place: .tailAppendEventTap,
            options: .listenOnly, eventsOfInterest: 1 << event.type.rawValue,
            callback: Self.callback, userInfo: context)
        guard let processTap, let sessionTap else {
            NSLog("Menu Pocket: native event delivery taps unavailable")
            cancel()
            return false
        }
        for tap in [processTap, sessionTap] {
            guard let source = CFMachPortCreateRunLoopSource(nil, tap, 0) else {
                cancel()
                return false
            }
            sources.append(source)
            CFRunLoopAddSource(CFRunLoopGetMain(), source, .commonModes)
            CGEvent.tapEnable(tap: tap, enable: true)
        }
        let expected = marker
        timeout = Task { [weak self] in
            do { try await Task.sleep(for: .milliseconds(150)) } catch { return }
            guard let self, self.marker == expected, self.isBusy else { return }
            NSLog("Menu Pocket: native event delivery timed out")
            self.cancel()
        }
        // Notify the item owner before routing the mouse event through the server.
        probe.postToPid(owner)
        return true
    }

    private func received(_ event: CGEvent) -> Bool {
        let tag = event.getIntegerValueField(.eventSourceUserData)
        if event.type == .null, tag == marker + 1, let next = events.first {
            if let processTap { CGEvent.tapEnable(tap: processTap, enable: false) }
            next.post(tap: .cgSessionEventTap)
            return true
        }
        guard tag == marker, let next = events.first, event.type == next.type else { return false }
        clearTaps()
        next.postToPid(owner)
        events.removeFirst()
        if events.isEmpty {
            release = nil
            restorePointer(immediately: false)
            NSLog("Menu Pocket: native move events delivered")
        } else {
            timeout = Task { [weak self] in
                do { try await Task.sleep(for: .milliseconds(30)) } catch { return }
                guard let self, self.isBusy else { return }
                _ = self.beginEvent()
            }
        }
        return false
    }

    private func clearTaps() {
        timeout?.cancel()
        timeout = nil
        for source in sources {
            CFRunLoopRemoveSource(CFRunLoopGetMain(), source, .commonModes)
        }
        sources.removeAll()
        for tap in [processTap, sessionTap].compactMap({ $0 }) { CFMachPortInvalidate(tap) }
        processTap = nil
        sessionTap = nil
        probe = nil
    }

    private static let callback: CGEventTapCallBack = { _, _, event, context in
        guard let context else { return Unmanaged.passUnretained(event) }
        let delivery = Unmanaged<MenuPocketEventDelivery>.fromOpaque(context).takeUnretainedValue()
        let consume = MainActor.assumeIsolated { delivery.received(event) }
        return consume ? nil : Unmanaged.passUnretained(event)
    }
}
